export const GENRES = [
  {
    judul: "Action",
    slug: "action",
    href: "/otakudesu/genres/action",
    otakudesuUrl: "https://otakudesu.cloud/genres/action/",
  },
  {
    judul: "Adventure",
    slug: "adventure",
    href: "/otakudesu/genres/adventure",
    otakudesuUrl: "https://otakudesu.cloud/genres/adventure/",
  },
  {
    judul: "Comedy",
    slug: "comedy",
    href: "/otakudesu/genres/comedy",
    otakudesuUrl: "https://otakudesu.cloud/genres/comedy/",
  },
  {
    judul: "Demons",
    slug: "demons",
    href: "/otakudesu/genres/demons",
    otakudesuUrl: "https://otakudesu.cloud/genres/demons/",
  },
  {
    judul: "Drama",
    slug: "drama",
    href: "/otakudesu/genres/drama",
    otakudesuUrl: "https://otakudesu.cloud/genres/drama/",
  },
  {
    judul: "Ecchi",
    slug: "ecchi",
    href: "/otakudesu/genres/ecchi",
    otakudesuUrl: "https://otakudesu.cloud/genres/ecchi/",
  },
  {
    judul: "Fantasy",
    slug: "fantasy",
    href: "/otakudesu/genres/fantasy",
    otakudesuUrl: "https://otakudesu.cloud/genres/fantasy/",
  },
  {
    judul: "Game",
    slug: "game",
    href: "/otakudesu/genres/game",
    otakudesuUrl: "https://otakudesu.cloud/genres/game/",
  },
  {
    judul: "Harem",
    slug: "harem",
    href: "/otakudesu/genres/harem",
    otakudesuUrl: "https://otakudesu.cloud/genres/harem/",
  },
  {
    judul: "Historical",
    slug: "historical",
    href: "/otakudesu/genres/historical",
    otakudesuUrl: "https://otakudesu.cloud/genres/historical/",
  },
  {
    judul: "Horror",
    slug: "horror",
    href: "/otakudesu/genres/horror",
    otakudesuUrl: "https://otakudesu.cloud/genres/horror/",
  },
  {
    judul: "Josei",
    slug: "josei",
    href: "/otakudesu/genres/josei",
    otakudesuUrl: "https://otakudesu.cloud/genres/josei/",
  },
  {
    judul: "Magic",
    slug: "magic",
    href: "/otakudesu/genres/magic",
    otakudesuUrl: "https://otakudesu.cloud/genres/magic/",
  },
  {
    judul: "Martial Arts",
    slug: "martial-arts",
    href: "/otakudesu/genres/martial-arts",
    otakudesuUrl: "https://otakudesu.cloud/genres/martial-arts/",
  },
  {
    judul: "Mecha",
    slug: "mecha",
    href: "/otakudesu/genres/mecha",
    otakudesuUrl: "https://otakudesu.cloud/genres/mecha/",
  },
  {
    judul: "Military",
    slug: "military",
    href: "/otakudesu/genres/military",
    otakudesuUrl: "https://otakudesu.cloud/genres/military/",
  },
  {
    judul: "Music",
    slug: "music",
    href: "/otakudesu/genres/music",
    otakudesuUrl: "https://otakudesu.cloud/genres/music/",
  },
  {
    judul: "Mystery",
    slug: "mystery",
    href: "/otakudesu/genres/mystery",
    otakudesuUrl: "https://otakudesu.cloud/genres/mystery/",
  },
  {
    judul: "Psychological",
    slug: "psychological",
    href: "/otakudesu/genres/psychological",
    otakudesuUrl: "https://otakudesu.cloud/genres/psychological/",
  },
  {
    judul: "Parody",
    slug: "parody",
    href: "/otakudesu/genres/parody",
    otakudesuUrl: "https://otakudesu.cloud/genres/parody/",
  },
  {
    judul: "Police",
    slug: "police",
    href: "/otakudesu/genres/police",
    otakudesuUrl: "https://otakudesu.cloud/genres/police/",
  },
  {
    judul: "Romance",
    slug: "romance",
    href: "/otakudesu/genres/romance",
    otakudesuUrl: "https://otakudesu.cloud/genres/romance/",
  },
  {
    judul: "Samurai",
    slug: "samurai",
    href: "/otakudesu/genres/samurai",
    otakudesuUrl: "https://otakudesu.cloud/genres/samurai/",
  },
  {
    judul: "School",
    slug: "school",
    href: "/otakudesu/genres/school",
    otakudesuUrl: "https://otakudesu.cloud/genres/school/",
  },
  {
    judul: "Sci-Fi",
    slug: "sci-fi",
    href: "/otakudesu/genres/sci-fi",
    otakudesuUrl: "https://otakudesu.cloud/genres/sci-fi/",
  },
  {
    judul: "Seinen",
    slug: "seinen",
    href: "/otakudesu/genres/seinen",
    otakudesuUrl: "https://otakudesu.cloud/genres/seinen/",
  },
  {
    judul: "Shoujo",
    slug: "shoujo",
    href: "/otakudesu/genres/shoujo",
    otakudesuUrl: "https://otakudesu.cloud/genres/shoujo/",
  },
  {
    judul: "Shoujo Ai",
    slug: "shoujo-ai",
    href: "/otakudesu/genres/shoujo-ai",
    otakudesuUrl: "https://otakudesu.cloud/genres/shoujo-ai/",
  },
  {
    judul: "Shounen",
    slug: "shounen",
    href: "/otakudesu/genres/shounen",
    otakudesuUrl: "https://otakudesu.cloud/genres/shounen/",
  },
  {
    judul: "Slice of Life",
    slug: "slice-of-life",
    href: "/otakudesu/genres/slice-of-life",
    otakudesuUrl: "https://otakudesu.cloud/genres/slice-of-life/",
  },
  {
    judul: "Sports",
    slug: "sports",
    href: "/otakudesu/genres/sports",
    otakudesuUrl: "https://otakudesu.cloud/genres/sports/",
  },
  {
    judul: "Space",
    slug: "space",
    href: "/otakudesu/genres/space",
    otakudesuUrl: "https://otakudesu.cloud/genres/space/",
  },
  {
    judul: "Super Power",
    slug: "super-power",
    href: "/otakudesu/genres/super-power",
    otakudesuUrl: "https://otakudesu.cloud/genres/super-power/",
  },
  {
    judul: "Supernatural",
    slug: "supernatural",
    href: "/otakudesu/genres/supernatural",
    otakudesuUrl: "https://otakudesu.cloud/genres/supernatural/",
  },
  {
    judul: "Thriller",
    slug: "thriller",
    href: "/otakudesu/genres/thriller",
    otakudesuUrl: "https://otakudesu.cloud/genres/thriller/",
  },
  {
    judul: "Vampire",
    slug: "vampire",
    href: "/otakudesu/genres/vampire",
    otakudesuUrl: "https://otakudesu.cloud/genres/vampire/",
  },
]

export const API_URL = "https://wajik-anime-api.vercel.app/otakudesu"
